export const LIGUES = [
  { id: 1,   nom: "Coupe du Monde" },
  { id: 4,   nom: "Euro (Championnat d'Europe)" },
  { id: 2,   nom: "Ligue des Champions (UEFA)" },
  { id: 3,   nom: "Ligue Europa (UEFA)" },
  { id: 848, nom: "Ligue Conférence (UEFA)" },
  { id: 39,  nom: "Premier League (Angleterre)" },
  { id: 140, nom: "La Liga (Espagne)" },
  { id: 135, nom: "Serie A (Italie)" },
  { id: 78,  nom: "Bundesliga (Allemagne)" },
  { id: 61,  nom: "Ligue 1 (France)" },
  { id: 88,  nom: "Eredivisie (Pays-Bas)" },
  { id: 94,  nom: "Primeira Liga (Portugal)" },
  { id: 253, nom: "MLS (États-Unis/Canada)" },
  { id: 262, nom: "Liga MX (Mexique)" },
  { id: 71,  nom: "Brasileirão Série A (Brésil)" },
  { id: 128, nom: "Liga Profesional (Argentine)" },
  { id: 98,  nom: "J1 League (Japon)" },
  { id: 239, nom: "Primera A (Colombie)" },
  { id: 344, nom: "Primera División (Bolivie)" },
  { id: 242, nom: "Liga Pro Serie A (Équateur)" },
  { id: 268, nom: "Primera División (Uruguay)" },
  { id: 265, nom: "Primera División (Chili)" },
  { id: 281, nom: "Liga 1 (Pérou)" },
  { id: 169, nom: "Veikkausliiga (Finlande)" },
  { id: 113, nom: "Allsvenskan (Suède)" },
  { id: 103, nom: "Eliteserien (Norvège)" },
  { id: 9,   nom: "Copa América" },
  { id: 13,  nom: "Copa Libertadores" },
  { id: 11,  nom: "Copa Sudamericana" },
];
